/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e0e3e6',
        'surface': '#f7f9fc',
        'deep-ink': '#000000',
        'primary': '#001645',
        'on-primary': '#ffffff',
        'surface-dim': '#d8dadd',
        'outline-variant': '#c4c6d2',
        'on-secondary-container': '#004f69',
        'inverse-surface': '#2d3133',
        'surface-container-high': '#e6e8eb',
        'on-error-container': '#93000a',
        'tertiary': '#3e0002',
        'primary-fixed-dim': '#b3c5ff',
        'secondary': '#006686',
        'on-primary-fixed': '#001849',
        'tertiary-container': '#650006',
        'background': '#f7f9fc',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#93000d',
        'surface-gray': '#F4F4F4',
        'outline': '#747682',
        'surface-container': '#eceef1',
        'on-surface': '#191c1e',
        'on-error': '#ffffff',
        'secondary-fixed': '#c0e8ff',
        'on-surface-variant': '#444651',
        'on-secondary': '#ffffff',
        'primary-container': '#002970',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e0e3e6',
        'surface-container-low': '#f2f4f7',
        'inverse-on-surface': '#eff1f4',
        'primary-fixed': '#dae1ff',
        'heritage-red': '#E31E24',
        'on-background': '#191c1e',
        'error': '#ba1a1a',
        'on-secondary-fixed-variant': '#004d66',
        'trust-blue': '#002970',
        'surface-tint': '#3f5ba3',
        'tertiary-fixed': '#ffdad6',
        'tertiary-fixed-dim': '#ffb4ab',
        'on-secondary-fixed': '#001e2b',
        'on-primary-container': '#7893df',
        'surface-bright': '#f7f9fc',
        'action-cyan': '#00BAF2',
        'on-primary-fixed-variant': '#25438a',
        'on-tertiary-fixed': '#410002',
        'secondary-fixed-dim': '#71d2ff',
        'on-tertiary-container': '#ff6157',
        'inverse-primary': '#b3c5ff',
        'error-container': '#ffdad6',
        'secondary-container': '#2bc6ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'unit': '8px',
        'container-max': '1280px',
      },
      fontFamily: {
        'hanken': ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        'inter': ['Inter', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      animation: {
        'fade-in': 'fadeIn 0.25s ease-out',
        'slide-up': 'slideUp 0.35s ease-out',
        'pulse-ring': 'pulseRing 1.5s ease-out infinite',
        'wave': 'wave 1.2s ease-in-out infinite',
        'skeleton': 'skeleton 1.5s infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0', transform: 'translateY(6px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        pulseRing: { '0%': { transform: 'scale(1)', opacity: '1' }, '100%': { transform: 'scale(2.5)', opacity: '0' } },
        wave: { '0%, 100%': { transform: 'scaleY(0.4)' }, '50%': { transform: 'scaleY(1)' } },
        skeleton: { '0%': { backgroundPosition: '200% 0' }, '100%': { backgroundPosition: '-200% 0' } },
      },
    },
  },
  plugins: [],
};
