const axios = require('axios');
const sharp = require('sharp');
const supabase = require('../db/supabase');
const path = require('path');
const fs = require('fs');

const BACKDROPS = {
  studio_white: { r: 245, g: 245, b: 245 },
  neutral_beige: { r: 255, g: 248, b: 235 },
  dark_slate: { r: 51, g: 65, b: 85 },
  sage_green: { r: 209, g: 250, b: 229 },
};

const { execSync } = require('child_process');
const { v4: uuidv4 } = require('uuid');

async function removeBackground(imageBuffer) {
  const tempIn = path.join(__dirname, `temp_in_${uuidv4()}.jpg`);
  const tempOut = path.join(__dirname, `temp_out_${uuidv4()}.png`);

  try {
    console.log("⏳ Running Python-powered cloth segmentation (u2net_cloth_seg)...");
    fs.writeFileSync(tempIn, imageBuffer);

    const scriptPath = path.join(__dirname, 'remove_bg_helper.py');
    execSync(`python "${scriptPath}" "${tempIn}" "${tempOut}"`, { stdio: 'pipe' });

    if (!fs.existsSync(tempOut)) {
      throw new Error("Output image was not generated by helper script.");
    }

    const outputBuffer = fs.readFileSync(tempOut);
    console.log("✅ Saree background successfully removed locally!");
    return { buffer: outputBuffer, success: true };
  } catch (err) {
    console.warn("⚠️ Background removal fallback triggered:", err.message);
    return { buffer: imageBuffer, success: false };
  } finally {
    try { if (fs.existsSync(tempIn)) fs.unlinkSync(tempIn); } catch {}
    try { if (fs.existsSync(tempOut)) fs.unlinkSync(tempOut); } catch {}
  }
}

async function compositeOnBackdrop(fgBuffer, backdropName, bgRemovedSuccessfully = true) {
  const color = BACKDROPS[backdropName] || BACKDROPS.studio_white;

  const meta = await sharp(fgBuffer).metadata();
  const width = meta.width || 800;
  const height = meta.height || 1000;

  if (!bgRemovedSuccessfully) {
    // Dropback Fallback: Process full-bleed (no resizing/shrinking to prevent any borders/belts)
    // and apply studio-vibe color correction: raise brightness & saturation slightly
    const result = await sharp(fgBuffer)
      .modulate({
        brightness: 1.08,
        saturation: 1.15
      })
      .linear(1.05, -5) // subtle contrast boost
      .jpeg({ quality: 95 })
      .toBuffer();

    return result;
  } else {
    // Normal blend with extracted transparent mask
    const backdrop = await sharp({
      create: { width, height, channels: 3, background: color },
    }).png().toBuffer();

    const result = await sharp(backdrop)
      .composite([{ input: fgBuffer, blend: 'over' }])
      .jpeg({ quality: 92 })
      .toBuffer();

    return result;
  }
}

async function processAndUpload(imageBuffer, productId, backdropName) {
  const bgResult = await removeBackground(imageBuffer);
  const enhanced = await compositeOnBackdrop(bgResult.buffer, backdropName || 'studio_white', bgResult.success);

  const fileName = `enhanced/${productId}/${Date.now()}.jpg`;
  const { error } = await supabase.storage
    .from('product-images')
    .upload(fileName, enhanced, { contentType: 'image/jpeg', upsert: true });

  if (error) throw error;

  const { data: urlData } = supabase.storage.from('product-images').getPublicUrl(fileName);
  return urlData.publicUrl;
}

async function uploadRaw(imageBuffer, productId) {
  const fileName = `raw/${productId}/${Date.now()}.jpg`;
  const { error } = await supabase.storage
    .from('product-images')
    .upload(fileName, imageBuffer, { contentType: 'image/jpeg', upsert: true });

  if (error) throw error;
  const { data: urlData } = supabase.storage.from('product-images').getPublicUrl(fileName);
  return urlData.publicUrl;
}

module.exports = {
  processAndUpload,
  uploadRaw,
  removeBackground,
  compositeOnBackdrop
};
