const PDFDocument = require('pdfkit');

function generateExportDeclaration(product, hsnSuggestion) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ size: 'A4', margin: 60 });

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(36).fillColor('#FF000040').rotate(-45, { origin: [300, 420] });
    doc.text('DRAFT — NOT A LEGAL DOCUMENT', 80, 300, { align: 'center' });
    doc.rotate(45, { origin: [300, 420] });

    doc.fillColor('#002E6E').fontSize(22).font('Helvetica-Bold');
    doc.text('DRAFT EXPORT DECLARATION', { align: 'center' });
    doc.moveDown(0.3);
    doc.fillColor('#00BAF2').fontSize(10).font('Helvetica');
    doc.text('Generated by SarasTM · AI-Assisted · NOT A LEGAL FILING DOCUMENT', { align: 'center' });
    doc.moveDown(1.5);

    doc.moveTo(60, doc.y).lineTo(535, doc.y).strokeColor('#002E6E').lineWidth(2).stroke();
    doc.moveDown(1);

    const row = (label, value) => {
      doc.fillColor('#002E6E').font('Helvetica-Bold').fontSize(10).text(label, { continued: true, width: 200 });
      doc.fillColor('#444444').font('Helvetica').text(value);
      doc.moveDown(0.5);
    };

    row('Exporter:', product.artisans?.name || 'Artisan Name');
    row('Region:', product.artisans?.region || product.region_label || 'India');
    row('Product:', product.title);
    row('Description:', product.story_en?.slice(0, 150) + '...');
    row('HSN Code (AI Suggested):', hsnSuggestion?.code || 'Pending');
    row('HSN Description:', hsnSuggestion?.description || '');
    row('AI Confidence:', hsnSuggestion?.confidence || 'N/A');
    row('Price (INR):', `₹${product.price_inr?.toLocaleString()}`);
    row('Price (USD):', `$${product.price_usd}`);
    row('Generated On:', new Date().toLocaleDateString('en-IN'));

    doc.moveDown(2);
    doc.moveTo(60, doc.y).lineTo(535, doc.y).strokeColor('#CCCCCC').lineWidth(1).stroke();
    doc.moveDown(1);

    doc.fillColor('#FF4444').font('Helvetica-Bold').fontSize(9);
    doc.text('IMPORTANT DISCLAIMER', { align: 'center' });
    doc.moveDown(0.5);
    doc.fillColor('#666666').font('Helvetica').fontSize(8);
    doc.text(
      'This document is an AI-generated DRAFT for reference purposes only. It is NOT a legally valid export declaration or shipping document. All HSN code suggestions must be verified by a licensed customs agent or Chartered Accountant before any export filing. SarasTM makes no warranty as to the accuracy of HSN classifications.',
      { align: 'justify' }
    );

    doc.end();
  });
}

function generateEFIRA(order, payout) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ size: 'A4', margin: 60 });

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(28).fillColor('#FF000040').rotate(-45, { origin: [300, 420] });
    doc.text('SANDBOX DEMO — NOT A VALID FIRA', 80, 300, { align: 'center' });
    doc.rotate(45, { origin: [300, 420] });

    doc.fillColor('#002E6E').fontSize(22).font('Helvetica-Bold');
    doc.text('FOREIGN INWARD REMITTANCE ADVICE', { align: 'center' });
    doc.moveDown(0.3);
    doc.fillColor('#00BAF2').fontSize(10).font('Helvetica');
    doc.text('SANDBOX / TEST MODE — SarasTM Demo Document', { align: 'center' });
    doc.moveDown(1.5);

    doc.moveTo(60, doc.y).lineTo(535, doc.y).strokeColor('#002E6E').lineWidth(2).stroke();
    doc.moveDown(1);

    const row = (label, value) => {
      doc.fillColor('#002E6E').font('Helvetica-Bold').fontSize(10).text(label, { continued: true, width: 200 });
      doc.fillColor('#444444').font('Helvetica').text(value);
      doc.moveDown(0.5);
    };

    row('FIRA Reference:', `SARAS-TEST-${payout.id?.slice(0, 8).toUpperCase()}`);
    row('Order ID:', order.id);
    row('Buyer Email:', order.buyer_email);
    row('Amount Received:', `${order.currency} ${order.amount}`);
    row('Amount (INR Equivalent):', `₹${payout.amount_inr?.toLocaleString()}`);
    row('Payout Date:', new Date(payout.paid_at || Date.now()).toLocaleDateString('en-IN'));
    row('Remittance Purpose:', 'Export of Handicrafts (PP0 — Software/Services)');
    row('Mode:', 'Test/Sandbox — Razorpay Test Mode');

    doc.moveDown(2);
    doc.fillColor('#FF4444').font('Helvetica-Bold').fontSize(9);
    doc.text('IMPORTANT DISCLAIMER', { align: 'center' });
    doc.moveDown(0.5);
    doc.fillColor('#666666').font('Helvetica').fontSize(8);
    doc.text('This is a SANDBOX/DEMO document generated for demonstration purposes only. It is NOT a valid Foreign Inward Remittance Advice (FIRA) or any legally recognized financial document. No real money has been transferred. Real cross-border payments require an AD-II licensed Payment Aggregator under RBI/FEMA regulations.', { align: 'justify' });

    doc.end();
  });
}

module.exports = { generateExportDeclaration, generateEFIRA };
